import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#31302b",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#002111",
        "secondary-fixed": "#ffdea4",
        "secondary-container": "#fcca66",
        "outline-variant": "#c0c9c0",
        "inverse-on-surface": "#f4f0e8",
        "on-surface": "#1c1c17",
        "surface-container-highest": "#e6e2da",
        "on-primary-container": "#72a484",
        "tertiary-container": "#27350d",
        "surface-dim": "#dddad2",
        "surface-container": "#f1ede6",
        "on-tertiary-fixed": "#131f00",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f7f3eb",
        "secondary-fixed-dim": "#f0bf5c",
        "on-primary-fixed-variant": "#1f5036",
        tertiary: "#131f00",
        "tertiary-fixed-dim": "#bbce97",
        "on-secondary-fixed-variant": "#5d4200",
        "on-background": "#1c1c17",
        secondary: "#7b5900",
        "on-error": "#ffffff",
        error: "#ba1a1a",
        surface: "#fdf9f1",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        primary: "#002211",
        outline: "#717972",
        "surface-tint": "#38684c",
        "primary-container": "#033921",
        "surface-variant": "#e6e2da",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#9fd2b0",
        "on-secondary-container": "#755400",
        "surface-container-high": "#ebe8e0",
        "tertiary-fixed": "#d7eab1",
        "on-secondary-fixed": "#261900",
        "on-tertiary-fixed-variant": "#3d4c21",
        "surface-bright": "#fdf9f1",
        "primary-fixed-dim": "#9fd2b0",
        "on-surface-variant": "#414942",
        "primary-fixed": "#baefcb",
        "error-container": "#ffdad6",
        background: "#fdf9f1",
        "on-tertiary-container": "#8d9f6c",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "gutter-mobile": "0.75rem",
        gutter: "1.25rem",
        "margin-mobile": "1rem",
        margin: "2rem",
      },
      fontFamily: {
        "playfair": ["Playfair Display", "serif"],
        "inter": ["Inter", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "title-sm": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "title-md": ["16px", { lineHeight: "22px", fontWeight: "600" }],
        "title-lg": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "500" }],
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
